//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetSale.Web {
    
    
    public partial class ProductDetails {
        
        /// <summary>
        /// ReviewList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetSale.Web.UserControls.ReviewListUserControl ReviewList;
        
        /// <summary>
        /// AlsoBought control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetSale.Web.UserControls.AlsoBoughtUserControl AlsoBought;
    }
}
