//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetSale.Web.UserControls {
    
    
    public partial class ProductCatalogUserControl {
        
        /// <summary>
        /// EventNamesNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetSale.Web.UserControls.EventNamesUserControl EventNamesNew;
        
        /// <summary>
        /// EventNamesHit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetSale.Web.UserControls.EventNamesUserControl EventNamesHit;
        
        /// <summary>
        /// EventNamesBest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetSale.Web.UserControls.EventNamesUserControl EventNamesBest;
    }
}
