// <auto-generated />
namespace MemoEngine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoomSpeakAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomSpeakAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201608062238051_RoomSpeak Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
